apiVersion: v1
kind: Service
metadata:
  name: courses-code
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
  selector:
    app: courses-code
