apiVersion: apps/v1
kind: Deployment
metadata:
  name: courses-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: courses-test
  template:
    metadata:
      labels:
        app: courses-test
    spec:
      containers:
        - name: courses-test
          image: sufiyashabai/courses-test:IMAGE_TAG
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: mysql-configmap
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: mysql-configmap
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: mysql-configmap
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: DB_PASSWORD
